# Generated by Django 2.1.5 on 2019-12-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField(default='1.1.1.1')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField(default='1.1.1.1')),
                ('state', models.CharField(max_length=20)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm_list.Server')),
            ],
        ),
    ]
