# Generated by Django 2.0 on 2019-12-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
        ),
        migrations.AddField(
            model_name='vm',
            name='ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
        ),
        migrations.AddField(
            model_name='vm',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
